const domains=[
{id:'medicine',name:'Medicine & health',icon:'🩺',cluster:'People',tone:'#dce9df',hook:'From spotting patterns to planning care, with human consent and clinical judgement.',impact:[5,4,3,5,5],skills:['biology','empathy','evidence'],nodes:['diagnostic support','drug discovery','care navigation','medical imaging'],human:'Clinical judgement, empathy and accountability',risk:'Bias, privacy, unsafe certainty and unequal access',future:'Clinician + AI safety lead'},
{id:'law',name:'Law & public policy',icon:'⚖️',cluster:'Society',tone:'#efd9c9',hook:'AI can search, compare and draft. People still interpret rights, intent and consequences.',impact:[4,5,3,4,4],skills:['reasoning','writing','ethics'],nodes:['case research','contract review','policy simulation','access to justice'],human:'Interpretation, negotiation and duty to clients',risk:'Fabricated citations, hidden bias and due-process failures',future:'AI assurance counsel'},
{id:'engineering',name:'Engineering',icon:'⚙️',cluster:'Build',tone:'#d8e6eb',hook:'Generative design and simulation shorten iteration; safety remains engineered, tested and signed.',impact:[5,4,5,3,4],skills:['physics','systems','testing'],nodes:['generative design','digital twins','predictive maintenance','safety analysis'],human:'Trade-offs, physical constraints and public safety',risk:'Simulation error, brittle automation and weak validation',future:'Human-AI systems engineer'},
{id:'computing',name:'Computing & data',icon:'💻',cluster:'Build',tone:'#d8dfef',hook:'Code becomes faster to produce, so problem framing, verification and security matter more.',impact:[5,5,5,4,5],skills:['logic','debugging','security'],nodes:['code copilots','data analysis','cyber defence','model operations'],human:'Architecture, threat judgement and validation',risk:'Insecure code, data leakage and automation debt',future:'AI platform engineer'},
{id:'science',name:'Science & research',icon:'🔬',cluster:'Discover',tone:'#d9ebdc',hook:'AI finds patterns and proposes candidates; experiments decide what is true.',impact:[5,5,4,4,5],skills:['method','statistics','curiosity'],nodes:['literature mapping','hypothesis generation','lab automation','climate models'],human:'Causal reasoning, experimental design and scepticism',risk:'Spurious patterns, irreproducibility and data provenance',future:'Computational research lead'},
{id:'business',name:'Business & entrepreneurship',icon:'🚀',cluster:'Markets',tone:'#f1d9ba',hook:'Small teams can research, prototype and serve customers faster, if they solve a real need.',impact:[5,5,4,5,4],skills:['strategy','sales','operations'],nodes:['market sensing','rapid prototyping','customer support','decision intelligence'],human:'Taste, accountability and customer trust',risk:'Copycat products, weak evidence and opaque decisions',future:'AI-native venture operator'},
{id:'finance',name:'Finance & economics',icon:'📈',cluster:'Markets',tone:'#e4dfbd',hook:'Models can detect patterns and automate controls; humans own risk appetite and fiduciary duty.',impact:[5,5,4,5,4],skills:['maths','risk','regulation'],nodes:['fraud detection','scenario modelling','research synthesis','financial inclusion'],human:'Risk judgement, context and responsibility',risk:'Feedback loops, exclusion and false precision',future:'Model risk strategist'},
{id:'design',name:'Design & architecture',icon:'✏️',cluster:'Create',tone:'#e7ced9',hook:'AI multiplies options; designers decide what is useful, humane and buildable.',impact:[4,5,5,3,4],skills:['taste','research','spatial thinking'],nodes:['concept generation','user research','rapid visualisation','building performance'],human:'Taste, accessibility and lived context',risk:'Sameness, copied styles and excluded users',future:'Computational design director'},
{id:'media',name:'Media & journalism',icon:'🎙️',cluster:'Create',tone:'#ecd0c3',hook:'Production gets easier while verification, source trust and original reporting become scarcer.',impact:[5,5,4,4,5],skills:['storytelling','verification','media literacy'],nodes:['research desk','translation','personalisation','synthetic media'],human:'Source judgement, public interest and voice',risk:'Deepfakes, propaganda, attribution and trust collapse',future:'Authenticity editor'},
{id:'arts',name:'Arts & entertainment',icon:'🎭',cluster:'Create',tone:'#dfd2ea',hook:'AI becomes an instrument for iteration; authorship and meaning still come from people.',impact:[4,5,5,3,4],skills:['craft','voice','collaboration'],nodes:['music sketches','story worlds','game characters','interactive performance'],human:'Intent, cultural context and creative direction',risk:'Consent, copyright, homogenisation and labour impact',future:'Human-AI creative producer'},
{id:'education',name:'Education',icon:'📚',cluster:'People',tone:'#f0dfad',hook:'Tutoring can adapt minute by minute, but learning still needs effort, belonging and good teachers.',impact:[5,5,4,5,5],skills:['metacognition','questioning','communication'],nodes:['adaptive tutor','feedback coach','lesson design','accessibility'],human:'Motivation, pastoral care and learning design',risk:'Dependency, surveillance and incorrect teaching',future:'AI learning designer'},
{id:'climate',name:'Climate & agriculture',icon:'🌱',cluster:'Planet',tone:'#cfe2c9',hook:'Sensors and models help use land, water and energy more precisely.',impact:[5,4,4,5,4],skills:['ecology','geospatial','fieldwork'],nodes:['crop intelligence','weather risk','grid optimisation','biodiversity monitoring'],human:'Local knowledge, stewardship and trade-offs',risk:'Data gaps, farmer exclusion and rebound effects',future:'Climate intelligence agronomist'},
{id:'trades',name:'Trades & manufacturing',icon:'🛠️',cluster:'Build',tone:'#e7d6bd',hook:'AI guides inspection and maintenance; physical skill and safe execution stay human-centred.',impact:[4,3,4,5,3],skills:['making','safety','diagnosis'],nodes:['visual inspection','robot collaboration','maintenance guidance','quality control'],human:'Dexterity, site judgement and safety ownership',risk:'Deskilling, unsafe automation and worker surveillance',future:'Smart maintenance specialist'},
{id:'logistics',name:'Logistics & aviation',icon:'✈️',cluster:'Systems',tone:'#cee0e5',hook:'Prediction improves routes and flow; resilient operations still need human command.',impact:[5,5,3,5,4],skills:['operations','geography','risk'],nodes:['route optimisation','demand planning','fleet maintenance','disruption response'],human:'Exception handling, command and safety culture',risk:'Cascading failures, cyberattack and over-optimisation',future:'Autonomous operations controller'},
{id:'hospitality',name:'Hospitality & tourism',icon:'🏨',cluster:'People',tone:'#f0d6c0',hook:'AI personalises planning and operations; warmth and local knowledge remain the experience.',impact:[4,4,3,5,3],skills:['service','languages','culture'],nodes:['trip planning','revenue planning','guest support','food operations'],human:'Hospitality, improvisation and cultural sensitivity',risk:'Surveillance, dynamic-pricing harm and generic experiences',future:'Experience intelligence manager'},
{id:'sports',name:'Sports & wellness',icon:'🏃',cluster:'People',tone:'#d9e4c4',hook:'AI can analyse movement and recovery; coaches and clinicians set safe, human goals.',impact:[4,4,4,5,4],skills:['physiology','coaching','data literacy'],nodes:['performance analysis','injury prevention','scouting','fan experience'],human:'Motivation, wellbeing and ethical coaching',risk:'Health misuse, body surveillance and unfair advantage',future:'Performance data coach'}];
const metrics=['Task change','AI assistance','New roles','Human judgement','Need to verify'];
let state={view:'cards',filter:'All',query:'',compare:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function filtered(){return domains.filter(d=>(state.filter==='All'||d.cluster===state.filter)&&(`${d.name} ${d.hook} ${d.skills} ${d.nodes}`.toLowerCase().includes(state.query.toLowerCase())))}
function init(){const clusters=['All',...new Set(domains.map(d=>d.cluster))];$('#filters').innerHTML=clusters.map(x=>`<button data-filter="${x}" class="${x==='All'?'active':''}">${x}</button>`).join('');bind();render();renderCompare()}
function bind(){$('#filters').onclick=e=>{if(!e.target.dataset.filter)return;state.filter=e.target.dataset.filter;$$('#filters button').forEach(b=>b.classList.toggle('active',b===e.target));render()};$('#search').oninput=e=>{state.query=e.target.value;render()};$('.view-switch').onclick=e=>{if(!e.target.dataset.view)return;state.view=e.target.dataset.view;$$('.view-switch button').forEach(b=>b.classList.toggle('active',b===e.target));render()};$('#content').onclick=e=>{const b=e.target.closest('[data-open],[data-compare],[data-node]');if(!b)return;if(b.dataset.open)openDomain(b.dataset.open);if(b.dataset.node)openDomain(b.dataset.node,'nodes');if(b.dataset.compare)toggleCompare(b.dataset.compare)};$('#randomBtn').onclick=()=>openDomain(domains[Math.floor(Math.random()*domains.length)].id);$('#clearCompare').onclick=()=>{state.compare=[];renderCompare();render()};$('#compareBody').onclick=e=>{if(e.target.dataset.open)openDomain(e.target.dataset.open)};$('#modal').onclick=e=>{if(e.target.hasAttribute('data-close'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('#aboutBtn').onclick=()=>showAbout()}
function render(){const list=filtered();if(state.view==='cards')renderCards(list);if(state.view==='heatmap')renderHeat(list);if(state.view==='nodes')renderNodes(list)}
function renderCards(list){$('#content').innerHTML=`<div class="cards">${list.map(d=>`<article class="domain-card"><div class="card-top" style="--tone:${d.tone}"><span class="card-icon">${d.icon}</span><h3>${d.name}</h3></div><div class="card-body"><p>${d.hook}</p><div class="stats">${d.skills.map(x=>`<span>${x}</span>`).join('')}</div><div class="card-actions"><button data-compare="${d.id}">${state.compare.includes(d.id)?'Added ✓':'Compare'}</button><button class="open" data-open="${d.id}">Open map</button></div></div></article>`).join('')}</div>`}
function renderHeat(list){$('#content').innerHTML=`<div class="heatmap-wrap"><div class="heatmap"><div class="heat-head">Domain</div>${metrics.map(m=>`<div class="heat-head">${m}</div>`).join('')}${list.map(d=>`<div><strong>${d.icon} ${d.name}</strong></div>${d.impact.map((v,i)=>`<div class="heat-cell i${v}" data-open="${d.id}" title="${metrics[i]}: ${v}/5">${v}/5</div>`).join('')}`).join('')}</div></div><p class="micro">Scenario heatmap: 1 = limited near-term effect, 5 = major effect. Tap a score for its domain detail.</p>`}
function renderNodes(list){const shown=list.slice(0,16),cx=50,cy=50;$('#content').innerHTML=`<div class="node-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${shown.map((d,i)=>{let a=2*Math.PI*i/shown.length,x=cx+40*Math.cos(a),y=cy+41*Math.sin(a);return `<line x1="50" y1="50" x2="${x}" y2="${y}" stroke="#b5aa9d" stroke-width=".3"/>`}).join('')}</svg><div class="hub">HUMAN<br>+ AI</div>${shown.map((d,i)=>{let a=2*Math.PI*i/shown.length,x=cx+40*Math.cos(a),y=cy+41*Math.sin(a);return `<button class="node" style="--x:${x}%;--y:${y}%;--tone:${d.tone}" data-node="${d.id}">${d.icon} ${d.name.split(' & ')[0]}</button>`}).join('')}</div>`}
function toggleCompare(id){if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<2)state.compare.push(id);else state.compare=[state.compare[1],id];render();renderCompare();if(state.compare.length===2)$('#compare').scrollIntoView({behavior:'smooth'})}
function renderCompare(){if(!state.compare.length){$('#compareBody').className='compare-empty';$('#compareBody').textContent='Tap “Compare” on any two domain cards.';return}const ds=state.compare.map(id=>domains.find(d=>d.id===id));if(ds.length===1){$('#compareBody').className='compare-empty';$('#compareBody').textContent=`${ds[0].name} added. Choose one more world.`;return}const rows=[['Core AI role',ds[0].nodes.slice(0,2).join(' + '),ds[1].nodes.slice(0,2).join(' + ')],['Human edge',ds[0].human,ds[1].human],['Main risk',ds[0].risk,ds[1].risk],['Skills',ds[0].skills.join(' · '),ds[1].skills.join(' · ')],['Emerging role',ds[0].future,ds[1].future]];$('#compareBody').className='compare-grid';$('#compareBody').innerHTML=`<div class="compare-label">Dimension</div>${ds.map(d=>`<div><button class="ghost" data-open="${d.id}">${d.icon} ${d.name}</button></div>`).join('')}${rows.map(r=>r.map((v,i)=>`<div class="${i===0?'compare-label':''}">${v}</div>`).join('')).join('')}`}
function openDomain(id,tab='overview'){const d=domains.find(x=>x.id===id);$('#modalBody').innerHTML=`<div class="detail-hero" style="--tone:${d.tone}"><p class="eyebrow">${d.cluster.toUpperCase()} · STUDENT PATHWAY</p><h2>${d.icon} ${d.name}</h2><p>${d.hook}</p></div><div class="detail-tabs"><button data-tab="overview">Overview</button><button data-tab="swimlane">Swim lane</button><button data-tab="nodes">Nodes</button><button data-tab="risks">Guardrails</button><button data-tab="jev">Jev contract</button></div><div id="detailPanel" class="detail-panel"></div>`;$('#modal').hidden=false;document.body.classList.add('lock');$$('.detail-tabs button').forEach(b=>{b.onclick=()=>detailPanel(d,b.dataset.tab);b.classList.toggle('active',b.dataset.tab===tab)});detailPanel(d,tab)}
function detailPanel(d,tab){$$('.detail-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const p=$('#detailPanel');if(tab==='overview')p.innerHTML=`<h3>What changes</h3><p>${d.hook}</p><h3>The human edge</h3><p>${d.human}.</p><h3>Skills to start now</h3><div class="node-list">${d.skills.map((x,i)=>`<div class="node-detail"><strong>${i+1}. ${x}</strong><p>Practise through a small real-world project, explain your choices, then verify the outcome.</p></div>`).join('')}<div class="node-detail"><strong>Emerging role</strong><p>${d.future}</p></div></div>`;if(tab==='swimlane')p.innerHTML=`<h3>How a task moves</h3><div class="heatmap-wrap"><div class="swim"><div></div><div>Frame</div><div>Assist</div><div>Verify</div><div>Decide</div><div class="lane">Student</div><div>Ask a precise question</div><div class="step-chip" style="--tone:${d.tone}">Use AI to explore options</div><div>Check sources and assumptions</div><div>Explain the choice</div><div class="lane">AI layer</div><div>Structure the request</div><div class="step-chip" style="--tone:${d.tone}">Retrieve · classify · generate</div><div>Return evidence + uncertainty</div><div>No final authority</div><div class="lane">Teacher / expert</div><div>Set the learning goal</div><div>Coach the process</div><div>Challenge weak reasoning</div><div>Own safety and assessment</div></div></div>`;if(tab==='nodes')p.innerHTML=`<h3>Clickable work nodes</h3><div class="node-list">${d.nodes.map((n,i)=>`<div class="node-detail"><strong>${n}</strong><p><b>AI:</b> accelerates pattern-finding and first drafts.<br><b>Student:</b> frames, checks and explains.<br><b>Proof:</b> source trail plus a tested output.</p></div>`).join('')}</div>`;if(tab==='risks')p.innerHTML=`<h3>Where it can fail</h3><div class="risk"><strong>${d.risk}</strong></div><h3>Five student guardrails</h3><ol><li>Never treat fluent output as proof.</li><li>Keep personal and confidential data out.</li><li>Trace important claims to a real source.</li><li>Ask who could be excluded or harmed.</li><li>Keep a human responsible for the final decision.</li></ol>`;if(tab==='jev')p.innerHTML=`<h3>Typed content and inference contract</h3><p>Jev keeps every domain fast and comparable by requiring the same shape before content reaches the UI.</p><div class="jev">{\n  "domain": "${d.id}",\n  "task": "${d.nodes[0]}",\n  "ai_role": "assist",\n  "human_authority": "${d.human}",\n  "evidence_required": true,\n  "risk": "${d.risk}",\n  "confidence": 0.0,\n  "next_action": "verify | practise | ask_expert"\n}</div><p>In this prototype the content is static and deterministic. A production inference endpoint is not connected yet.</p>`}
function showAbout(){$('#modalBody').innerHTML=`<div class="detail-hero" style="--tone:#dce9df"><p class="eyebrow">HOW IT WORKS</p><h2>One map, three ways to think</h2></div><h3>Cards</h3><p>Start with a domain and its human edge.</p><h3>Heatmap</h3><p>Compare where task change, assistance, verification and judgement are strongest.</p><h3>Node map</h3><p>See the connected landscape, then drill into each world.</p><h3>What is real today</h3><p>The app is an educational prototype with curated static content. Jev is represented as the typed contract layer; live model inference, accounts, saved progress and external evidence feeds are not connected.</p>`;$('#modal').hidden=false;document.body.classList.add('lock')}
function closeModal(){$('#modal').hidden=true;document.body.classList.remove('lock')}
init();
